
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Label lblTournamentViewerMain;

	private global::Gtk.EventBox eventbox5;

	private global::Gtk.Label lblTournamentName;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Label lblTournamentViewerRound;

	private global::Gtk.EventBox eventbox6;

	private global::Gtk.ComboBox combobox1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Tournament Viewer");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.lblTournamentViewerMain = new global::Gtk.Label();
		this.lblTournamentViewerMain.Name = "lblTournamentViewerMain";
		this.lblTournamentViewerMain.LabelProp = global::Mono.Unix.Catalog.GetString("Tournament:");
		this.hbox5.Add(this.lblTournamentViewerMain);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.lblTournamentViewerMain]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.eventbox5 = new global::Gtk.EventBox();
		this.eventbox5.Name = "eventbox5";
		// Container child eventbox5.Gtk.Container+ContainerChild
		this.lblTournamentName = new global::Gtk.Label();
		this.lblTournamentName.Name = "lblTournamentName";
		this.lblTournamentName.LabelProp = global::Mono.Unix.Catalog.GetString("<none>");
		this.eventbox5.Add(this.lblTournamentName);
		this.hbox5.Add(this.eventbox5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.eventbox5]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox7.Add(this.hbox5);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox5]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.lblTournamentViewerRound = new global::Gtk.Label();
		this.lblTournamentViewerRound.Name = "lblTournamentViewerRound";
		this.lblTournamentViewerRound.LabelProp = global::Mono.Unix.Catalog.GetString("Round");
		this.hbox7.Add(this.lblTournamentViewerRound);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.lblTournamentViewerRound]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.eventbox6 = new global::Gtk.EventBox();
		this.eventbox6.Name = "eventbox6";
		// Container child eventbox6.Gtk.Container+ContainerChild
		this.combobox1 = global::Gtk.ComboBox.NewText();
		this.combobox1.Name = "combobox1";
		this.eventbox6.Add(this.combobox1);
		this.hbox7.Add(this.eventbox6);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.eventbox6]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox7.Add(this.hbox7);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.Add(this.vbox7);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 526;
		this.DefaultHeight = 300;
		this.Show();
	}
}
