
// This file has been generated by the GUI designer. Do not modify.
namespace TrackerDesktopUI
{
	public partial class CreateTournament
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TrackerDesktopUI.CreateTournament
			this.Name = "TrackerDesktopUI.CreateTournament";
			this.Title = global::Mono.Unix.Catalog.GetString("CreateTournament");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
