
// This file has been generated by the GUI designer. Do not modify.
namespace TrackerDesktopUI
{
	public partial class CreatePrize
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget TrackerDesktopUI.CreatePrize
			this.Name = "TrackerDesktopUI.CreatePrize";
			this.Title = global::Mono.Unix.Catalog.GetString("CreatePrize");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
